/**
 * DO NOT EDIT -- this file is auto-generated by scripts/generate_worker_recipes.py
 * from recipes/*.yaml. To update, run: python scripts/generate_worker_recipes.py
 */

/** A sparagmos recipe definition. */
export interface Recipe {
  slug: string;
  inputs: number;
  name: string;
  description: string;
}

/** All available recipes with their required input counts. */
export const RECIPES: readonly Recipe[] = [
  { slug: "acid-wash", inputs: 3, name: "Acid Wash", description: "Three images run through spectral transformation — their frequencies scrambled and redistributed..." },
  { slug: "binary-archaeology", inputs: 4, name: "Binary Archaeology", description: "Each of the four images is dithered to a different binary palette — different dithering algorithm..." },
  { slug: "broadcast-static", inputs: 3, name: "Broadcast Static", description: "Three images converted to sound and back — each through a different acoustic treatment, each emer..." },
  { slug: "broken-mirror", inputs: 5, name: "Broken Mirror", description: "Five images shattered along Voronoi seams with deliberate gaps, as if the mirror holding all five..." },
  { slug: "chimera-engine", inputs: 5, name: "Chimera Engine", description: "Three images Voronoi-fragmented into organic cells, blended with a fourth, then edge-masked again..." },
  { slug: "collage-mask-collage", inputs: 4, name: "Collage Mask Collage", description: "Two images collaged into a mosaic grid, then a third used as an edge stencil to cut through the g..." },
  { slug: "collage-surgery", inputs: 4, name: "Collage Surgery", description: "Four images cut into strips and edge-masked three times in alternating rounds — each pass strips..." },
  { slug: "collage-through-glass", inputs: 4, name: "Collage Through Glass", description: "Three images are mosaiced into a composite grid — an even tiling of three borrowed worlds." },
  { slug: "collage-veil", inputs: 5, name: "Collage Veil", description: "All five images are first mosaiced into a single tiled composite — five worlds locked into one grid." },
  { slug: "composite-quilt", inputs: 5, name: "Composite Quilt", description: "Images A and B are grid-fragmented into rectangular patches — a quilt of borrowed tiles from two..." },
  { slug: "contrast-surgery", inputs: 4, name: "Contrast Surgery", description: "Image A undergoes extreme channel surgery — massive RGB offsets pull its color registers apart un..." },
  { slug: "cross-pollinate", inputs: 5, name: "Cross Pollinate", description: "Two parallel edge-mask chains cross-pollinate their results." },
  { slug: "cut-paste-repeat", inputs: 5, name: "Cut Paste Repeat", description: "The name is the recipe: mask, paste, cut, paste, mask again." },
  { slug: "cutout-mosaic", inputs: 5, name: "Cutout Mosaic", description: "Three images are mosaiced into a grid composite — fragments locked into cells, a surface of borro..." },
  { slug: "data-rot", inputs: 3, name: "Data Rot", description: "Three images subjected to byte-level corruption before any composition — the damage is baked in f..." },
  { slug: "dissolve-cascade", inputs: 4, name: "Dissolve Cascade", description: "Four images dissolved in waves: screen blend accumulates the light, gradient masking carves the e..." },
  { slug: "double-exposure", inputs: 2, name: "Double Exposure", description: "Two images burned onto the same film." },
  { slug: "double-masked-collage", inputs: 4, name: "Double Masked Collage", description: "A double masking sandwich: fragment, edge-mask, scatter-collage, luminance- mask again." },
  { slug: "dream-archaeology", inputs: 5, name: "Dream Archaeology", description: "Each image is PCA-decomposed to different component depths — A stripped to near-structural ghost,..." },
  { slug: "dream-cutout", inputs: 3, name: "Dream Cutout", description: "Image A is deepdreamed heavily — the network projects its hallucinations across every surface." },
  { slug: "dream-dissolve", inputs: 2, name: "Dream Dissolve", description: "Two images each sent through deep neural hallucination — the network finds eyes and feathers in e..." },
  { slug: "dream-erosion", inputs: 4, name: "Dream Erosion", description: "A is deepdreamed heavily, colonized by neural hallucinations until the original photograph is bar..." },
  { slug: "dream-fragment-storm", inputs: 5, name: "Dream Fragment Storm", description: "Three images are deepdreamed — A, B, and C each acquiring dense neural hallucinations." },
  { slug: "dream-mask-dream", inputs: 4, name: "Dream Mask Dream", description: "A triple dream-mask cycle." },
  { slug: "dream-mask", inputs: 4, name: "Dream Mask", description: "Image A is deepdreamed heavily — the network hallucinates eyes, pagodas, dog-faces across every s..." },
  { slug: "dream-stencil", inputs: 4, name: "Dream Stencil", description: "A is deepdreamed at high intensity until its surface is dense with hallucinated forms — eyes insi..." },
  { slug: "dream-within-dream", inputs: 3, name: "Dream Within Dream", description: "Recursive hallucination in three passes." },
  { slug: "edge-ghosts", inputs: 3, name: "Edge Ghosts", description: "Phantom outlines from one image haunting another." },
  { slug: "edge-lattice", inputs: 5, name: "Edge Lattice", description: "Edge masking applied to every consecutive pair of five images — a cascades into b, b into c, c in..." },
  { slug: "edge-weave", inputs: 5, name: "Edge Weave", description: "Five images woven together through their own structural edges." },
  { slug: "entropy-garden", inputs: 5, name: "Entropy Garden", description: "Five images each deepdreamed into proliferating hallucinations before being assembled into a mosaic." },
  { slug: "exquisite-corpse", inputs: 3, name: "Exquisite Corpse", description: "The surrealist parlor game." },
  { slug: "feedback-loop", inputs: 2, name: "Feedback Loop", description: "Compose, destroy, re-compose the wreckage, destroy again." },
  { slug: "fossil-record", inputs: 3, name: "Fossil Record", description: "Geological strata." },
  { slug: "fracture-and-mask", inputs: 4, name: "Fracture and Mask", description: "A shatter-fragment sandwich with edge and luminance masking on either side." },
  { slug: "fragment-storm", inputs: 5, name: "Fragment Storm", description: "Five images shattered twice with different piece counts — first a coarse shattering, then edge ma..." },
  { slug: "ghost-overlay", inputs: 2, name: "Ghost Overlay", description: "A haunting: A's edges become a soft veil cast over B with high feathering, so the transition is a..." },
  { slug: "gradient-reveal", inputs: 4, name: "Gradient Reveal", description: "A three-stage revelation where each step peels back a different layer." },
  { slug: "hallucinated-quilt", inputs: 5, name: "Hallucinated Quilt", description: "Five images dreamed at different iteration counts — 5, 10, 15, 20, and 25 — creating a spectrum f..." },
  { slug: "hallucination-collage", inputs: 5, name: "Hallucination Collage", description: "All five inputs are deepdreamed at escalating intensities — A barely touched at 5 iterations, B a..." },
  { slug: "holographic-interference", inputs: 3, name: "Holographic Interference", description: "Three images processed through spectral decomposition and channel aberration, then stacked via di..." },
  { slug: "interference-mask", inputs: 4, name: "Interference Mask", description: "Images A and B are blended at difference mode — each pixel becomes the absolute distance between..." },
  { slug: "kaleidoscope-collapse", inputs: 5, name: "Kaleidoscope Collapse", description: "Five sources collaged into a mosaic, then the mosaic is shattered and edge-masked against one of..." },
  { slug: "kaleidoscope-dream", inputs: 5, name: "Kaleidoscope Dream", description: "All five inputs are deepdreamed independently, each colonized by the network's preferred hallucin..." },
  { slug: "layered-cutwork", inputs: 4, name: "Layered Cutwork", description: "Three sequential rounds of mask then collage then mask: the image accumulates wounds with each pass." },
  { slug: "letterpress", inputs: 4, name: "Letterpress", description: "Image A is dithered with Atkinson, which creates the tight, typographic dot-and-space pattern tha..." },
  { slug: "luminance-layers", inputs: 4, name: "Luminance Layers", description: "Four images revealed through four different luminance thresholds of the same reference source." },
  { slug: "mask-and-glitch", inputs: 3, name: "Mask and Glitch", description: "Image A is edge-masked onto B, producing a clean structural composite." },
  { slug: "mask-and-scatter", inputs: 5, name: "Mask and Scatter", description: "Image A is luminance-masked onto B, cutting A's bright silhouette into B's flesh." },
  { slug: "mask-cascade", inputs: 4, name: "Mask Cascade", description: "Four images layered through four successive mask operations, each using a different mask source —..." },
  { slug: "mask-collage-fusion", inputs: 5, name: "Mask Collage Fusion", description: "Image A is luminance-masked onto B — A's bright zones punch through to reveal B beneath, a hard s..." },
  { slug: "mask-erosion", inputs: 4, name: "Mask Erosion", description: "Three sequential edge masks with increasing feather — a progressive erosion where each pass softe..." },
  { slug: "mask-everything", inputs: 5, name: "Mask Everything", description: "Maximum masking: every image pair gets composited through a mask before anything else happens." },
  { slug: "mask-feedback", inputs: 5, name: "Mask Feedback", description: "A chain of masks where each output becomes the input mask for the next stage." },
  { slug: "mask-fragment-cycle", inputs: 5, name: "Mask Fragment Cycle", description: "A full cycle: mask, then cut, then mask again, then paste." },
  { slug: "masked-archaeology", inputs: 5, name: "Masked Archaeology", description: "Each input is PCA-decomposed to a different depth — A stripped to 1 principal component (near-pur..." },
  { slug: "masked-tapestry", inputs: 5, name: "Masked Tapestry", description: "Five images woven into a layered tapestry through successive masking." },
  { slug: "mosaic-dissolution", inputs: 5, name: "Mosaic Dissolution", description: "Five sources tiled into a mosaic, then the mosaic itself is fragmented and pixel-sorted into dust." },
  { slug: "mosaic-rebirth", inputs: 5, name: "Mosaic Rebirth", description: "Five sources assembled into a mosaic, sorted by pixel luminance into streaming vertical rivers, t..." },
  { slug: "negative-space", inputs: 4, name: "Negative Space", description: "Two masking operations, each using the opposite of what the other reveals." },
  { slug: "neural-chimera", inputs: 3, name: "Neural Chimera", description: "Three images deepdreamed at different neural layers then Voronoi-fragmented together." },
  { slug: "neural-mask-cascade", inputs: 4, name: "Neural Mask Cascade", description: "Four images, each deepdreamed independently, then chained through a cascade of dream-as-mask oper..." },
  { slug: "neural-tapestry", inputs: 5, name: "Neural Tapestry", description: "Three of the five inputs are deepdreamed — A, B, and C each acquire the network's hallucinated fo..." },
  { slug: "noise-cathedral", inputs: 4, name: "Noise Cathedral", description: "Three noise masks at escalating thresholds cut random windows between four images, building layer..." },
  { slug: "palimpsest-ii", inputs: 5, name: "Palimpsest II", description: "The manuscript overwritten so many times the original is unreadable." },
  { slug: "palimpsest", inputs: 4, name: "Palimpsest", description: "A manuscript overwritten and overwritten again." },
  { slug: "phantom-dream", inputs: 4, name: "Phantom Dream", description: "A and B are both deepdreamed — two photographs each colonized by the network's hallucinations ind..." },
  { slug: "phantom-limb", inputs: 2, name: "Phantom Limb", description: "One image's edge structure is cut out and laid over another — not the image itself, only its outl..." },
  { slug: "photogram", inputs: 4, name: "Photogram", description: "In the darkroom, a photogram is made by placing objects directly on light-sensitive paper and exp..." },
  { slug: "recursive-stencil", inputs: 5, name: "Recursive Stencil", description: "Five-deep recursive stenciling where each image's PCA structure is used as a luminance mask for t..." },
  { slug: "sediment-core", inputs: 3, name: "Sediment Core", description: "Three images arranged as horizontal strata — the slow accumulation of time rendered as a geologic..." },
  { slug: "shape-imposition", inputs: 5, name: "Shape Imposition", description: "Image A is PCA-reduced to a single principal component — its entire visual complexity collapsed t..." },
  { slug: "signal-bleed", inputs: 3, name: "Signal Bleed", description: "Three VHS signals bleeding into each other on a bad splitter." },
  { slug: "silhouette-collage", inputs: 4, name: "Silhouette Collage", description: "Image A is PCA-decomposed to 2 principal components — stripped to the barest structural silhouett..." },
  { slug: "silhouette-swap", inputs: 5, name: "Silhouette Swap", description: "A chain of five images where each one's PCA silhouette is used as the hard mask to cut the next." },
  { slug: "simple-cutout", inputs: 2, name: "Simple Cutout", description: "The most direct use of masking: A's edge skeleton is cut clean into B." },
  { slug: "sorted-mask", inputs: 3, name: "Sorted Mask", description: "Image A is pixel-sorted by brightness, generating long streaks that streak upward through the frame." },
  { slug: "spectral-mask", inputs: 4, name: "Spectral Mask", description: "Four images processed spectrally and then masked in pairs, with the pair results blended and dith..." },
  { slug: "spectral-merge", inputs: 2, name: "Spectral Merge", description: "Two signals in frequency space, destructively interfered." },
  { slug: "spectral-stencil", inputs: 3, name: "Spectral Stencil", description: "Image A is bandpass-filtered in frequency space, stripping its low and high frequencies to leave..." },
  { slug: "stamp-collection", inputs: 5, name: "Stamp Collection", description: "Five images are each fragmented into irregular pieces — the first pass shatters them into raw fra..." },
  { slug: "stencil-burn", inputs: 4, name: "Stencil Burn", description: "Image A is dithered to a near-binary stencil — its shapes reduced to stark positive and negative..." },
  { slug: "stencil-mosaic", inputs: 5, name: "Stencil Mosaic", description: "Image A is dithered to thermal — reduced to pure heat-map extremes — then used as a hard threshol..." },
  { slug: "stratum-shift", inputs: 4, name: "Stratum Shift", description: "Four images built into geological strata through strip collage, then seam-carved to warp the faul..." },
  { slug: "structural-echo", inputs: 4, name: "Structural Echo", description: "Image A's edge structure is applied three times to create a progressive echo effect." },
  { slug: "surveillance-decay", inputs: 4, name: "Surveillance Decay", description: "Four feeds arranged in the classic CCTV quad-view — the administrative gaze that watches everythi..." },
  { slug: "tectonic-overlap", inputs: 4, name: "Tectonic Overlap", description: "Continental plates of image data, shifted and overlapping." },
  { slug: "text-ghost", inputs: 4, name: "Text Ghost", description: "Image A is PCA-decomposed to just 1-2 principal components — its texture and color stripped away..." },
  { slug: "threshold-cascade", inputs: 4, name: "Threshold Cascade", description: "Four mask_composite operations at four ascending threshold bands — 40, 80, 150, and 200 — each cu..." },
  { slug: "torn-collage", inputs: 4, name: "Torn Collage", description: "Four images shattered like a mirror dropped on concrete." },
  { slug: "total-chaos", inputs: 5, name: "Total Chaos", description: "Every technique thrown into one sequence." },
  { slug: "triple-mask", inputs: 3, name: "Triple Mask", description: "Three images, two mask operations." },
  { slug: "two-face", inputs: 2, name: "Two Face", description: "A luminance mask splits image A at its median brightness — the bright half stays A, the dark half..." },
  { slug: "voronoi-chimera", inputs: 3, name: "Voronoi Chimera", description: "Faces and forms fused at Voronoi cell boundaries." },
  { slug: "wax-museum", inputs: 3, name: "Wax Museum", description: "Three images each passed through style transfer — their surfaces repainted in the manner of some..." },
  { slug: "x-ray-composite", inputs: 2, name: "X-Ray Composite", description: "One image is decomposed to its principal components — stripped to structural essentials, the eige..." },
] as const;

const slugSet = new Set(RECIPES.map((r) => r.slug));

/** Check whether a slug corresponds to a valid recipe. */
export function isValidRecipe(slug: string): boolean {
  return slugSet.has(slug);
}

/** Look up a recipe by slug, or undefined if not found. */
export function getRecipe(slug: string): Recipe | undefined {
  return RECIPES.find((r) => r.slug === slug);
}

/**
 * Format the full recipe list for Slack display, grouped by input count.
 * Uses Slack mrkdwn formatting.
 */
export function formatRecipeList(): string {
  const grouped = new Map<number, Recipe[]>();

  for (const recipe of RECIPES) {
    const list = grouped.get(recipe.inputs);
    if (list) {
      list.push(recipe);
    } else {
      grouped.set(recipe.inputs, [recipe]);
    }
  }

  const sortedKeys = [...grouped.keys()].sort((a, b) => a - b);

  const sections = sortedKeys.map((count) => {
    const recipes = grouped.get(count)!;
    const recipeLines = recipes.map((r) => `\`${r.slug}\` \u2014 ${r.name}`).join("\n");
    return `*${count} inputs:*\n${recipeLines}`;
  });

  return `*Available Recipes (${RECIPES.length} total):*\n\n${sections.join("\n\n")}`;
}

/**
 * Find recipes whose slugs contain the given substring.
 * Returns up to 5 matches for use in "did you mean?" suggestions.
 */
export function suggestRecipes(input: string): Recipe[] {
  const lower = input.toLowerCase();
  return RECIPES.filter((r) => r.slug.includes(lower)).slice(0, 5);
}
