#!/usr/bin/env python3
"""Generate worker/src/recipes.ts from recipes/*.yaml.

Reads all YAML recipe files from the recipes directory and generates a
TypeScript module that the Cloudflare Worker uses for recipe validation,
listing, and suggestion. Run this whenever recipes are added or modified.

Usage:
    python scripts/generate_worker_recipes.py
    python scripts/generate_worker_recipes.py --recipes-dir path/to/recipes --output path/to/recipes.ts
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml


def find_repo_root() -> Path:
    """Find the repo root by looking for the recipes/ directory."""
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    if (repo_root / "recipes").is_dir():
        return repo_root
    if (Path.cwd() / "recipes").is_dir():
        return Path.cwd()
    return repo_root


def truncate_description(desc: str, max_len: int = 100) -> str:
    """Extract the first sentence of a description, truncated to max_len chars."""
    if not desc:
        return ""
    # Collapse whitespace/newlines
    collapsed = re.sub(r"\s+", " ", desc.strip())
    # Try to cut at first sentence boundary
    match = re.match(r"^(.+?[.!?])\s", collapsed)
    sentence = match.group(1) if match else collapsed
    if len(sentence) <= max_len:
        return sentence
    return sentence[: max_len - 3].rstrip() + "..."


def escape_ts_string(s: str) -> str:
    """Escape a string for use in a TypeScript double-quoted string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def load_recipes(recipes_dir: Path) -> list[dict]:
    """Load all YAML recipes and return sorted list of recipe metadata."""
    recipes = []
    for path in sorted(recipes_dir.glob("*.yaml")):
        with open(path) as f:
            data = yaml.safe_load(f)
        if not data:
            continue
        slug = path.stem
        recipes.append({
            "slug": slug,
            "inputs": data.get("inputs", 1),
            "name": data.get("name", slug),
            "description": truncate_description(data.get("description", "")),
        })
    return recipes


def generate_typescript(recipes: list[dict]) -> str:
    """Generate the TypeScript source for recipes.ts."""
    lines = [
        "/**",
        " * DO NOT EDIT -- this file is auto-generated by scripts/generate_worker_recipes.py",
        " * from recipes/*.yaml. To update, run: python scripts/generate_worker_recipes.py",
        " */",
        "",
        "/** A sparagmos recipe definition. */",
        "export interface Recipe {",
        "  slug: string;",
        "  inputs: number;",
        "  name: string;",
        "  description: string;",
        "}",
        "",
        "/** All available recipes with their required input counts. */",
        "export const RECIPES: readonly Recipe[] = [",
    ]

    for r in recipes:
        slug = escape_ts_string(r["slug"])
        name = escape_ts_string(r["name"])
        desc = escape_ts_string(r["description"])
        lines.append(
            f'  {{ slug: "{slug}", inputs: {r["inputs"]}, '
            f'name: "{name}", description: "{desc}" }},'
        )

    lines.append("] as const;")
    lines.append("")
    lines.append('const slugSet = new Set(RECIPES.map((r) => r.slug));')
    lines.append("")
    lines.append("/** Check whether a slug corresponds to a valid recipe. */")
    lines.append("export function isValidRecipe(slug: string): boolean {")
    lines.append("  return slugSet.has(slug);")
    lines.append("}")
    lines.append("")
    lines.append("/** Look up a recipe by slug, or undefined if not found. */")
    lines.append("export function getRecipe(slug: string): Recipe | undefined {")
    lines.append("  return RECIPES.find((r) => r.slug === slug);")
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Format the full recipe list for Slack display, grouped by input count.")
    lines.append(" * Uses Slack mrkdwn formatting.")
    lines.append(" */")
    lines.append("export function formatRecipeList(): string {")
    lines.append("  const grouped = new Map<number, Recipe[]>();")
    lines.append("")
    lines.append("  for (const recipe of RECIPES) {")
    lines.append("    const list = grouped.get(recipe.inputs);")
    lines.append("    if (list) {")
    lines.append("      list.push(recipe);")
    lines.append("    } else {")
    lines.append("      grouped.set(recipe.inputs, [recipe]);")
    lines.append("    }")
    lines.append("  }")
    lines.append("")
    lines.append("  const sortedKeys = [...grouped.keys()].sort((a, b) => a - b);")
    lines.append("")
    lines.append("  const sections = sortedKeys.map((count) => {")
    lines.append("    const recipes = grouped.get(count)!;")
    lines.append('    const recipeLines = recipes.map((r) => `\\`${r.slug}\\` \\u2014 ${r.name}`).join("\\n");')
    lines.append('    return `*${count} inputs:*\\n${recipeLines}`;')
    lines.append("  });")
    lines.append("")
    lines.append('  return `*Available Recipes (${RECIPES.length} total):*\\n\\n${sections.join("\\n\\n")}`;')
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(" * Find recipes whose slugs contain the given substring.")
    lines.append(" * Returns up to 5 matches for use in \"did you mean?\" suggestions.")
    lines.append(" */")
    lines.append("export function suggestRecipes(input: string): Recipe[] {")
    lines.append("  const lower = input.toLowerCase();")
    lines.append('  return RECIPES.filter((r) => r.slug.includes(lower)).slice(0, 5);')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate worker/src/recipes.ts from YAML recipes")
    parser.add_argument("--recipes-dir", type=Path, default=None, help="Path to recipes directory")
    parser.add_argument("--output", type=Path, default=None, help="Output TypeScript file path")
    args = parser.parse_args()

    repo_root = find_repo_root()
    recipes_dir = args.recipes_dir or repo_root / "recipes"
    output_path = args.output or repo_root / "worker" / "src" / "recipes.ts"

    if not recipes_dir.is_dir():
        print(f"Error: recipes directory not found: {recipes_dir}", file=sys.stderr)
        sys.exit(1)

    recipes = load_recipes(recipes_dir)
    if not recipes:
        print("Error: no recipes found", file=sys.stderr)
        sys.exit(1)

    ts_source = generate_typescript(recipes)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_source)

    print(f"Generated {output_path} with {len(recipes)} recipes")


if __name__ == "__main__":
    main()
